[asio]
git-tree-sha1 = "c46fd8d39b2c9305ab1519a6f95ed8370b9e43fb"

    [[asio.download]]
    sha256 = "a95a6aff80deddd3edfc50679e1f4135135ab6edc65edb28ce89b93a7a3b3e9c"
    url = "https://github.com/JuliaBinaryWrappers/asio_jll.jl/releases/download/asio-v1.18.1+0/asio.v1.18.1.any.tar.gz"
