# Autogenerated wrapper script for asio_jll for any
export asio_hpp

JLLWrappers.@generate_wrapper_header("asio")
JLLWrappers.@declare_file_product(asio_hpp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        asio_hpp,
        "include/asio.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
